#!/bin/sh

src=`dirname $0`
src=`cd $src;pwd`
source $src/vault-misc $src

ensure_param_count_exit_usage $# 2 "<unit_name> <commit_message>"

name=$1
msg=$2

get_unit_and_enter $name

function add {
    if [ -d $1 ]; then
        git add $1 || error 3 "Can't add $1"
    fi
}

get_current_branch
if [ "$branch" != "master" ]; then
    error 22 "Submodule commit should be run only when on master, got $branch"
fi

processed=$(git status --porcelain -z | xargs -0 git vault-unit-status-process)
rc=$?
if [ $rc -ne 0 ]; then
    error $rc "Error processing status for $name"
elif [ "x$processed" != "x" ]; then
    git commit -m "$msg"
    echo $processed
else
    trace "Nothing to commit for $name"
fi


