#!/bin/sh

src=`dirname $0`
src=`cd $src;pwd`
source $src/the-vault_misc $src

ensure_param_count_exit_usage $# 2 "<unit_name> <commit_message>"

name=$1
msg=$2

get_unit_and_enter $name

function add {
    if [ -d $1 ]; then
        git add $1 || error 3 "Can't add $1"
    fi
}

get_current_branch
if [ "$branch" != "master" ]; then
    error 22 "Submodule commit should be run only when on master, got $branch"
fi

git status --porcelain -z | xargs -0 the-vault-submodule-status-process
git commit -a -m "vault-commit" \
    && git notes add -m "vault-commit-$msg" HEAD


