#!/bin/sh

src=`dirname $0`
src=`cd $src;pwd`
export PATH=$src:$PATH
source $src/the-vault_misc

ensure_param_count_exit_usage $# 2 "<unit_name> <commit_message>"

name=$1
msg=$2
get_root

unit=$root/$name
cd $unit || error 2 "Can't enter $unit"

function add {
    if [ -d $1 ]; then
        git add $1 || error 3 "Can't add $1"
    fi
}

git checkout master || error 99 "Can't checkout master for $name"
#git ls-files --deleted -z | xargs -0 git rm
git status --porcelain -z | xargs -0 the-vault-submodule-status-process
git commit -a -m "$msg"


