#!/bin/sh

src=`dirname $0`
src=`cd $src;pwd`
source $src/the-vault_misc $src

ensure_param_count_exit_usage $# 2 "<unit_name> <commit_message>"

name=$1
msg=$2

get_unit_and_enter $name

function add {
    if [ -d $1 ]; then
        git add $1 || error 3 "Can't add $1"
    fi
}

git checkout -f master || error 99 "Can't checkout master for $name"
git status --porcelain -z | xargs -0 the-vault-submodule-status-process
git commit -a -m "$msg"


