#!/bin/sh

src=`dirname $0`
src=`cd $src;pwd`
source $src/the-vault_misc $src

ensure_param_count_op_exit_usage $# -ge 1 "<unit_name> [is_store_blobs_separately]"
name=$1
shift;

ini_template=$src/vault-unit.template

if [ $# -eq 0 ]; then
    blob_separate=1
else
    blob_separate=$1
fi

get_root_and_enter

function git_add_init {
    git_dir=../.git/modules/$name/.git
    mkdir -p $git_dir
    git init --separate-git-dir $git_dir
}

git checkout $master \
    && mkdir $name \
    && cd $name \
    && git_add_init \
    && the-vault-submodule-config \
    && ini_set $ini_template core name $name > ./.vault-unit \
    && ini_set ./.vault-unit blob separate $blob_separate > ./.vault-unit \
    && git add .vault-unit \
    && check_vault_unit_compatible \
    && git commit -m "vault-config" \
    && git tag "vault-unit" \
    && cd $root \
    && git submodule add ./$name \
    && git add .gitmodules \
    && git commit -m "vault-submodule-add" \
    && git notes add -m "vault-submodule-add-$name"

