#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage $0 <src> <dst>"
    exit 1
fi

function error {
    echo "${@:2}" 1>&2;
    exit $1
}

src=$1
dst=$2
scripts=.vault-scripts

if ! [ -d $dst/$scripts ]; then
    mkdir $dst/$scripts
    if ! [ -d $dst/$scripts ]; then
        error 1 "Can't create $dst/$scripts"
    fi
fi
cp $src/the-vault*[^~] $src/*.template $src/*.awk $dst/$scripts \
    && cd $dst \
    && git add $scripts \
    && git commit -m "$scripts"
